### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by scharger** [alexandr-mironov/php-smpp#4]
https://github.com/alexandr-mironov/php-smpp/blob/6a906fadbea0ec35ff4bb0c72277e5d404dec122/src/transport/Socket.php#L311

**Comment by alexandr-mironov** [comment]
Hello, its not a bug, we close socket ip v6 in case we use socket ip v4,
this is legacy and need to refactor this but its not a bug.
TY for you issue, sorry for long time no answer
