### ISSUE TITLE
PHP8 compatibility

### ISSUE THREAD

**Issue by oc666** [alexandr-mironov/php-smpp#6]
Hello

Socket resource was change on PHP8 and it's class object instead of resource. 

Need to change the condition in [Socket.php](https://github.com/alexandr-mironov/php-smpp/blob/master/src/transport/Socket.php#L227) from:
`
if (!is_resource($this->socket)) return false;
`
to:
`
if (!is_resource($this->socket) && !$this->socket instanceof \Socket) return false;
`

More info can be found here: https://php.watch/versions/8.0/sockets-sockets-addressinfo#sockets-is-resource

**Comment by alexandr-mironov** [comment]
please use https://github.com/alexandr-mironov/php8-smpp
