### ISSUE TITLE
I want to use gsm-7 encoding 

### ISSUE THREAD

**Issue by mohammadrezare** [alexandr-mironov/php-smpp#9]
Hi guys,
Today, I want to send my message in gsm-7. However, it's not listed in supported encoding types.

**Comment by alexandr-mironov** [comment]
Hello,
as described in https://en.wikipedia.org/wiki/GSM_03.38
`GSM 03.38 defines GSM 7-bit default alphabet`
this encoding used as default (const \smpp\SMPP::DATA_CODING_DEFAULT)
you can compare translate map from \smpp\helpers\GsmEncoderHelper::utf8_to_gsm0338 with table from wiki page
please describe your problem more if i misunderstood your question
